title: REGINA Registro Nacional de Neoplasias en Asegurados de EsSalud
description: Módulo de autoaprendizaje para el Registro de cáncer de EsSalud
theme: just-the-docs

nav_enabled: true
heading_anchors: true
footer_content: "© 2025 OIIS - Built with Just the Docs"
math: true
